- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - scorecard-test
    - olm-bundle-validation
    image: quay.io/operator-framework/scorecard-test:v1.35.0
    labels:
      suite: olm
      test: olm-bundle-validation-test
- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - scorecard-test
    - olm-crds-have-validation
    image: quay.io/operator-framework/scorecard-test:v1.35.0
    labels:
      suite: olm
      test: olm-crds-have-validation-test
# - TODO(macao): This fails since VPA checkpoint does not have resources in CSV. Figure out how to fix this.
# - op: add
#   path: /stages/0/tests/-
#   value:
#     entrypoint:
#     - scorecard-test
#     - olm-crds-have-resources
#     image: quay.io/operator-framework/scorecard-test:v1.35.0
#     labels:
#       suite: olm
#       test: olm-crds-have-resources-test
- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - scorecard-test
    - olm-spec-descriptors
    image: quay.io/operator-framework/scorecard-test:v1.35.0
    labels:
      suite: olm
      test: olm-spec-descriptors-test
- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - scorecard-test
    - olm-status-descriptors
    image: quay.io/operator-framework/scorecard-test:v1.35.0
    labels:
      suite: olm
      test: olm-status-descriptors-test
