apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-vertical-pod-autoscaler

images:
- name: quay.io/openshift/origin-vertical-pod-autoscaler-operator-catalog
  newName: PLACEHOLDER
  newTag: PLACEHOLDER

configMapGenerator:
- behavior: create
  literals:
  - OPERATOR_NAMESPACE_PLACEHOLDER
  name: vpa-operator-config

replacements:
- source:
    fieldPath: data.OPERATOR_NAMESPACE
    kind: ConfigMap
    name: vpa-operator-config
  targets:
  - fieldPaths:
    - spec.targetNamespaces.0
    select:
      kind: OperatorGroup
      name: vertical-pod-autoscaler-operator
  - fieldPaths:
    - spec.sourceNamespace
    select:
      kind: Subscription
      name: vertical-pod-autoscaler-operator

configurations:
- kustomizeconfig/cs-image-transformer.yaml

resources:
- vpa-catalogsource.yaml
- vpa-operatorgroup.yaml
- vpa-subscription.yaml
